// <auto-generated />
using System;
using IRSlovensko.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IRSlovensko.Migrations
{
    [DbContext(typeof(IRDbContext))]
    [Migration("20260428072633_AddStatistika")]
    partial class AddStatistika
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("IRSlovensko.Models.Ciselniky.CSIRKonaniaDovodUkonceniaProcesu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nazov")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CSIRKonaniaDovodUkonceniaProcesu");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nazov = "Inak"
                        },
                        new
                        {
                            Id = 2,
                            Nazov = "Iný dôvod"
                        },
                        new
                        {
                            Id = 3,
                            Nazov = "Nedá sa zostaviť splátkový kalendár správcom"
                        },
                        new
                        {
                            Id = 4,
                            Nazov = "Nedostatok majetku"
                        },
                        new
                        {
                            Id = 5,
                            Nazov = "Nesplnenie podmienok"
                        },
                        new
                        {
                            Id = 6,
                            Nazov = "Odmietnutie"
                        },
                        new
                        {
                            Id = 7,
                            Nazov = "Odsúhlasený plán"
                        },
                        new
                        {
                            Id = 8,
                            Nazov = "Osvedčená platobná schopnosť"
                        },
                        new
                        {
                            Id = 9,
                            Nazov = "Potvrdenie plánu súdom"
                        },
                        new
                        {
                            Id = 10,
                            Nazov = "Povolenie reštrukturalizácie"
                        },
                        new
                        {
                            Id = 11,
                            Nazov = "Skončené oddĺženie"
                        },
                        new
                        {
                            Id = 12,
                            Nazov = "Späťvzatie"
                        },
                        new
                        {
                            Id = 13,
                            Nazov = "Splnenie konečného rozvrhu"
                        },
                        new
                        {
                            Id = 14,
                            Nazov = "Splnenie rozvrhu výťažku"
                        },
                        new
                        {
                            Id = 15,
                            Nazov = "Určený splátkový kalendár"
                        },
                        new
                        {
                            Id = 16,
                            Nazov = "Vyhlásenie konkurzu"
                        },
                        new
                        {
                            Id = 17,
                            Nazov = "Zaplatenie splatných pohľadávok"
                        },
                        new
                        {
                            Id = 18,
                            Nazov = "Žiadny veriteľ"
                        });
                });

            modelBuilder.Entity("IRSlovensko.Models.Ciselniky.CSIRKonaniaOsobyRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nazov")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CSIRKonaniaOsobyRole");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nazov = "Dlžník"
                        },
                        new
                        {
                            Id = 2,
                            Nazov = "Navrhovateľ"
                        });
                });

            modelBuilder.Entity("IRSlovensko.Models.Ciselniky.CSIRKonaniaOsobyTyp", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nazov")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CSIRKonaniaOsobyTyp");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nazov = "Fyzická osoba"
                        },
                        new
                        {
                            Id = 2,
                            Nazov = "Fyzická osoba - podnikateľ"
                        },
                        new
                        {
                            Id = 3,
                            Nazov = "Právnická osoba"
                        });
                });

            modelBuilder.Entity("IRSlovensko.Models.Ciselniky.CSIRKonaniaStavKonania", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nazov")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CSIRKonaniaStavKonania");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nazov = "Prebiehajúce konanie"
                        },
                        new
                        {
                            Id = 2,
                            Nazov = "Prerušené konanie"
                        },
                        new
                        {
                            Id = 3,
                            Nazov = "Skončený proces"
                        },
                        new
                        {
                            Id = 4,
                            Nazov = "Začaté konanie"
                        },
                        new
                        {
                            Id = 5,
                            Nazov = "Začatý proces konania"
                        },
                        new
                        {
                            Id = 6,
                            Nazov = "Zastavené konanie"
                        });
                });

            modelBuilder.Entity("IRSlovensko.Models.Ciselniky.CSIRKonaniaTyp", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nazov")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CSIRKonaniaTyp");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nazov = "Likvidácia"
                        },
                        new
                        {
                            Id = 2,
                            Nazov = "Iné"
                        },
                        new
                        {
                            Id = 3,
                            Nazov = "Reštrukturalizácia"
                        },
                        new
                        {
                            Id = 4,
                            Nazov = "Oddĺženie - splátkový kalendár"
                        },
                        new
                        {
                            Id = 5,
                            Nazov = "Oddĺženie - konkurz"
                        },
                        new
                        {
                            Id = 6,
                            Nazov = "Malý konkurz"
                        },
                        new
                        {
                            Id = 7,
                            Nazov = "Konkurz"
                        },
                        new
                        {
                            Id = 8,
                            Nazov = "Verejná preventívna reštrukturalizácia"
                        });
                });

            modelBuilder.Entity("IRSlovensko.Models.Ciselniky.CSIRKonaniaTypPrideleniaSpravcu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nazov")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CSIRKonaniaTypPrideleniaSpravcu");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nazov = "Vymenovaný"
                        },
                        new
                        {
                            Id = 2,
                            Nazov = "Generovaný"
                        });
                });

            modelBuilder.Entity("IRSlovensko.Models.Ciselniky.CSIRKonaniaTypSpravcu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nazov")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CSIRKonaniaTypSpravcu");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nazov = "Riadny"
                        },
                        new
                        {
                            Id = 2,
                            Nazov = "Dozorný"
                        },
                        new
                        {
                            Id = 3,
                            Nazov = "Predbežný"
                        });
                });

            modelBuilder.Entity("IRSlovensko.Models.Ciselniky.CSIRVerejneOznamyDruhPodania", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nazov")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CSIRVerejneOznamyDruhPodania");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nazov = "Oznám o mieste a čase nahliadnutia do spisu"
                        },
                        new
                        {
                            Id = 2,
                            Nazov = "Oznám o zvolaní schôdze veriteľov"
                        },
                        new
                        {
                            Id = 3,
                            Nazov = "Zápisnica zo zasadnutia veriteľského výboru"
                        },
                        new
                        {
                            Id = 4,
                            Nazov = "Oznámenia súvisiace s dražbou majetku"
                        },
                        new
                        {
                            Id = 5,
                            Nazov = "Súpis všeobecnej podstaty"
                        },
                        new
                        {
                            Id = 6,
                            Nazov = "Súpis oddelenej podstaty"
                        },
                        new
                        {
                            Id = 7,
                            Nazov = "Zverejnenie návrhu čiastkového rozvrhu (všeobecná podstata)"
                        },
                        new
                        {
                            Id = 8,
                            Nazov = "Zverejnenie návrhu konečného výťažku (všeobecná podstata)"
                        },
                        new
                        {
                            Id = 9,
                            Nazov = "Doplnenie súpisu všeobecnej podstaty"
                        },
                        new
                        {
                            Id = 10,
                            Nazov = "Doplnenie súpisu oddelenej podstaty"
                        },
                        new
                        {
                            Id = 11,
                            Nazov = "Preradenie súpisovej zložky"
                        },
                        new
                        {
                            Id = 12,
                            Nazov = "Pripísanie poznámky o spornom zápise"
                        },
                        new
                        {
                            Id = 13,
                            Nazov = "Doplnenie alebo zmena poznámky o spornom zápise"
                        },
                        new
                        {
                            Id = 14,
                            Nazov = "Výmaz poznámky o spornom zápise"
                        },
                        new
                        {
                            Id = 15,
                            Nazov = "Vylúčenie súpisovej zložky majetku zo súpisu"
                        },
                        new
                        {
                            Id = 16,
                            Nazov = "Iné zverejnenie"
                        },
                        new
                        {
                            Id = 17,
                            Nazov = "Výzva zahraničným veriteľom na prihlásenie pohľadávok"
                        },
                        new
                        {
                            Id = 18,
                            Nazov = "Oznámenie čísla bankového účtu pre potreby popierania pohľadávok"
                        },
                        new
                        {
                            Id = 19,
                            Nazov = "Oznámenie o doručení prihlášky po uplynutí základnej prihlasovacej lehoty"
                        },
                        new
                        {
                            Id = 20,
                            Nazov = "Oznámenia súvisiace so speňažovaním majetku"
                        },
                        new
                        {
                            Id = 21,
                            Nazov = "Oznámenie o zostavení zoznamu pohľadávok (všeobecná podstata)"
                        },
                        new
                        {
                            Id = 22,
                            Nazov = "Oznámenie o zostavení zoznamu pohľadávok (oddelená podstata)"
                        },
                        new
                        {
                            Id = 23,
                            Nazov = "Zverejnenie návrhu čiastkového rozvrhu (oddelená podstata)"
                        },
                        new
                        {
                            Id = 24,
                            Nazov = "Zverejnenie návrhu konečného rozvrhu (oddelená podstata)"
                        },
                        new
                        {
                            Id = 25,
                            Nazov = "Zápisnica zo zasadnutia so zástupcom veriteľov"
                        },
                        new
                        {
                            Id = 26,
                            Nazov = "Oznám o zostavení návrhu splátkového kalendára"
                        },
                        new
                        {
                            Id = 27,
                            Nazov = "Oznám o nemožnosti zostaviť návrh splátkového kalendára"
                        },
                        new
                        {
                            Id = 28,
                            Nazov = "Oznám o zrušení konkurzu - splnenie rozvrhu výťažku"
                        },
                        new
                        {
                            Id = 29,
                            Nazov = "Oznám o zrušení konkurzu - podstata nepokryje náklady"
                        },
                        new
                        {
                            Id = 30,
                            Nazov = "Oznám o zrušení konkurzu - žiadny veriteľ do 90 dní"
                        },
                        new
                        {
                            Id = 31,
                            Nazov = "Oznám o zrušení konkurzu - zánik postavenia veriteľov"
                        },
                        new
                        {
                            Id = 32,
                            Nazov = "Oznám o skončení konania o návrhu na určenie SK"
                        },
                        new
                        {
                            Id = 33,
                            Nazov = "Oznám o uplatnení námietky voči zápisu majetku do súpisu"
                        },
                        new
                        {
                            Id = 34,
                            Nazov = "Prebiehajúca likvidácia"
                        },
                        new
                        {
                            Id = 35,
                            Nazov = "Likvidácia - prihlasovanie pohľadávok"
                        },
                        new
                        {
                            Id = 36,
                            Nazov = "Likvidácia - vyhotovenie zoznamu pohľadávok"
                        },
                        new
                        {
                            Id = 37,
                            Nazov = "Likvidácia - vyhotovenie zoznamu majetku"
                        },
                        new
                        {
                            Id = 38,
                            Nazov = "Podanie návrhu na vyhlásenie konkurzu (likvidátor)"
                        },
                        new
                        {
                            Id = 39,
                            Nazov = "Prerušená likvidácia - vyhlásený konkurz"
                        },
                        new
                        {
                            Id = 40,
                            Nazov = "Prerušená likvidácia"
                        },
                        new
                        {
                            Id = 41,
                            Nazov = "Skončené oznámením likvidátora"
                        },
                        new
                        {
                            Id = 42,
                            Nazov = "Schválenie účtovnej závierky a konečnej správy"
                        },
                        new
                        {
                            Id = 43,
                            Nazov = "Prebiehajúca dodatočná likvidácia"
                        },
                        new
                        {
                            Id = 44,
                            Nazov = "Dodatočná likvidácia - prihlasovanie pohľadávok"
                        },
                        new
                        {
                            Id = 45,
                            Nazov = "Dodatočná likvidácia - vyhotovenie zoznamu pohľadávok"
                        },
                        new
                        {
                            Id = 46,
                            Nazov = "Dodatočná likvidácia - vyhotovenie zoznamu majetku"
                        },
                        new
                        {
                            Id = 47,
                            Nazov = "Dodatočná likvidácia - podanie návrhu na vyhlásenie konkurzu"
                        },
                        new
                        {
                            Id = 48,
                            Nazov = "Dodatočná likvidácia - prerušené, vyhlásený konkurz"
                        },
                        new
                        {
                            Id = 49,
                            Nazov = "Dodatočná likvidácia - prerušené"
                        },
                        new
                        {
                            Id = 50,
                            Nazov = "Dodatočná likvidácia - skončené oznámením likvidátora"
                        },
                        new
                        {
                            Id = 51,
                            Nazov = "Dodatočná likvidácia - schválenie účtovnej závierky"
                        },
                        new
                        {
                            Id = 52,
                            Nazov = "Zvolanie schvaľovacej schôdze veriteľov po schválení plánu"
                        },
                        new
                        {
                            Id = 53,
                            Nazov = "Správa o postupe speňažovania"
                        },
                        new
                        {
                            Id = 54,
                            Nazov = "Zápisnica zo schôdze veriteľov"
                        },
                        new
                        {
                            Id = 55,
                            Nazov = "Zápisnica zo schvaľovacej schôdze veriteľov"
                        },
                        new
                        {
                            Id = 56,
                            Nazov = "Zvolanie schôdze veriteľského výboru na schválenie plánu"
                        },
                        new
                        {
                            Id = 57,
                            Nazov = "Záznam z online schôdze veriteľov"
                        },
                        new
                        {
                            Id = 58,
                            Nazov = "Oznámenie o zverejnení súpisu majetku"
                        },
                        new
                        {
                            Id = 59,
                            Nazov = "Ukončenie prihlasovania pohľadávok"
                        },
                        new
                        {
                            Id = 60,
                            Nazov = "Ukončenie prieskumu pohľadávok"
                        },
                        new
                        {
                            Id = 61,
                            Nazov = "Nedefinované"
                        });
                });

            modelBuilder.Entity("IRSlovensko.Models.Ciselniky.CSIRVerejneOznamyKonanieTyp", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nazov")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CSIRVerejneOznamyKonanieTyp");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nazov = "Konkurz"
                        },
                        new
                        {
                            Id = 2,
                            Nazov = "Malý konkurz"
                        },
                        new
                        {
                            Id = 3,
                            Nazov = "Reštrukturalizácia"
                        },
                        new
                        {
                            Id = 4,
                            Nazov = "Iné konania"
                        },
                        new
                        {
                            Id = 5,
                            Nazov = "Oddĺženie - konkurz"
                        },
                        new
                        {
                            Id = 6,
                            Nazov = "Oddĺženie - splátkový kalendár"
                        },
                        new
                        {
                            Id = 7,
                            Nazov = "Likvidácia"
                        },
                        new
                        {
                            Id = 8,
                            Nazov = "Verejná preventívna reštrukturalizácia"
                        });
                });

            modelBuilder.Entity("IRSlovensko.Models.Ciselniky.CSIRVerejneOznamyOznamTyp", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nazov")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CSIRVerejneOznamyOznamTyp");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nazov = "Oznám súdu"
                        },
                        new
                        {
                            Id = 2,
                            Nazov = "Oznám správcu"
                        });
                });

            modelBuilder.Entity("IRSlovensko.Models.Konanie", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DatumPodania")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DatumPoslednejUdalosti")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DatumPovoleniaOddlzenia")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DatumUkonceniaProcesu")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DatumZacatiaKonania")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DatumZacatiaProcesu")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DatumZavedeniaDozornejSpravy")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DovodUkonceniaProcesuId")
                        .HasColumnType("int");

                    b.Property<bool?>("MalyKonkurz")
                        .HasColumnType("bit");

                    b.Property<string>("PoslednaUdalost")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SpisovaZnackaSpravcu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SpisovaZnackaSudu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("StavKonaniaId")
                        .HasColumnType("int");

                    b.Property<string>("SudId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Sudca")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TypId")
                        .HasColumnType("int");

                    b.Property<string>("TypKonaniaPodlaUzemnejPlatnosti")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TypPrideleniaSpravcuId")
                        .HasColumnType("int");

                    b.Property<int?>("TypSpravcuId")
                        .HasColumnType("int");

                    b.Property<string>("ZnackaSpravcu")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("DovodUkonceniaProcesuId");

                    b.HasIndex("StavKonaniaId");

                    b.HasIndex("SudId");

                    b.HasIndex("TypId");

                    b.HasIndex("TypPrideleniaSpravcuId");

                    b.HasIndex("TypSpravcuId");

                    b.HasIndex("ZnackaSpravcu");

                    b.ToTable("Konania");
                });

            modelBuilder.Entity("IRSlovensko.Models.KonanieOsoba", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CisloRegistracie")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DatumNarodenia")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Iban")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ico")
                        .HasColumnType("nvarchar(450)");

                    b.Property<long>("IdKonania")
                        .HasColumnType("bigint");

                    b.Property<string>("Krajina")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Meno")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ObchodneMeno")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Obec")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrientacneCislo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PravnaForma")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Priezvisko")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Psc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Register")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RodneCislo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("StatneObcianstvo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SupisneCislo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Swift")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TitulPredMenom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TitulZaMenom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TypId")
                        .HasColumnType("int");

                    b.Property<string>("Ulica")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Ico")
                        .HasDatabaseName("IX_KonanieOsoba_Ico");

                    b.HasIndex("IdKonania");

                    b.HasIndex("RoleId");

                    b.HasIndex("TypId");

                    b.ToTable("KonaniaOsoby");
                });

            modelBuilder.Entity("IRSlovensko.Models.Spravca", b =>
                {
                    b.Property<string>("Znacka")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("DatumNarodenia")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DatumZapisu")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ico")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Krajina")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Meno")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ObchodneMeno")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Obec")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrientacneCislo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Priezvisko")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Psc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SupisneCislo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TitulPredMenom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TitulZaMenom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ulica")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Znacka");

                    b.ToTable("Spravcovia");
                });

            modelBuilder.Entity("IRSlovensko.Models.Statistika", b =>
                {
                    b.Property<DateTime>("DatumStahovania")
                        .HasColumnType("datetime2");

                    b.HasKey("DatumStahovania");

                    b.ToTable("Statistika");
                });

            modelBuilder.Entity("IRSlovensko.Models.Sud", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Nazov")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Sudy");
                });

            modelBuilder.Entity("IRSlovensko.Models.VerejnyOznam", b =>
                {
                    b.Property<long>("OznamId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("DatumVydania")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DruhPodaniaId")
                        .HasColumnType("int");

                    b.Property<long>("KonanieId")
                        .HasColumnType("bigint");

                    b.Property<int?>("KonanieTypId")
                        .HasColumnType("int");

                    b.Property<bool?>("ObsahujePrilohy")
                        .HasColumnType("bit");

                    b.Property<int?>("OznamTypId")
                        .HasColumnType("int");

                    b.Property<string>("SpisovaZnackaSpravcovskehoSpisu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SpisovaZnackaSudnehoSpisu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SudKod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SudNazov")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Text")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TextDruh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TextHlavicka")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TextOdovodnenie")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TextOznam")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TextPoucenie")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TextRozhodnutie")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("OznamId");

                    b.HasIndex("DruhPodaniaId");

                    b.HasIndex("KonanieId")
                        .HasDatabaseName("IX_VerejnyOznam_KonanieId");

                    b.HasIndex("KonanieTypId");

                    b.HasIndex("OznamTypId");

                    b.ToTable("VerejneOznamy");
                });

            modelBuilder.Entity("IRSlovensko.Models.Konanie", b =>
                {
                    b.HasOne("IRSlovensko.Models.Ciselniky.CSIRKonaniaDovodUkonceniaProcesu", "DovodUkonceniaProcesu")
                        .WithMany()
                        .HasForeignKey("DovodUkonceniaProcesuId");

                    b.HasOne("IRSlovensko.Models.Ciselniky.CSIRKonaniaStavKonania", "StavKonania")
                        .WithMany()
                        .HasForeignKey("StavKonaniaId");

                    b.HasOne("IRSlovensko.Models.Sud", "Sud")
                        .WithMany()
                        .HasForeignKey("SudId");

                    b.HasOne("IRSlovensko.Models.Ciselniky.CSIRKonaniaTyp", "Typ")
                        .WithMany()
                        .HasForeignKey("TypId");

                    b.HasOne("IRSlovensko.Models.Ciselniky.CSIRKonaniaTypPrideleniaSpravcu", "TypPrideleniaSpravcu")
                        .WithMany()
                        .HasForeignKey("TypPrideleniaSpravcuId");

                    b.HasOne("IRSlovensko.Models.Ciselniky.CSIRKonaniaTypSpravcu", "TypSpravcu")
                        .WithMany()
                        .HasForeignKey("TypSpravcuId");

                    b.HasOne("IRSlovensko.Models.Spravca", "Spravca")
                        .WithMany()
                        .HasForeignKey("ZnackaSpravcu");

                    b.Navigation("DovodUkonceniaProcesu");

                    b.Navigation("Spravca");

                    b.Navigation("StavKonania");

                    b.Navigation("Sud");

                    b.Navigation("Typ");

                    b.Navigation("TypPrideleniaSpravcu");

                    b.Navigation("TypSpravcu");
                });

            modelBuilder.Entity("IRSlovensko.Models.KonanieOsoba", b =>
                {
                    b.HasOne("IRSlovensko.Models.Konanie", "Konanie")
                        .WithMany("KonaniaOsoby")
                        .HasForeignKey("IdKonania")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IRSlovensko.Models.Ciselniky.CSIRKonaniaOsobyRole", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId");

                    b.HasOne("IRSlovensko.Models.Ciselniky.CSIRKonaniaOsobyTyp", "Typ")
                        .WithMany()
                        .HasForeignKey("TypId");

                    b.Navigation("Konanie");

                    b.Navigation("Role");

                    b.Navigation("Typ");
                });

            modelBuilder.Entity("IRSlovensko.Models.VerejnyOznam", b =>
                {
                    b.HasOne("IRSlovensko.Models.Ciselniky.CSIRVerejneOznamyDruhPodania", "DruhPodania")
                        .WithMany()
                        .HasForeignKey("DruhPodaniaId");

                    b.HasOne("IRSlovensko.Models.Konanie", "Konanie")
                        .WithMany()
                        .HasForeignKey("KonanieId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IRSlovensko.Models.Ciselniky.CSIRVerejneOznamyKonanieTyp", "KonanieTyp")
                        .WithMany()
                        .HasForeignKey("KonanieTypId");

                    b.HasOne("IRSlovensko.Models.Ciselniky.CSIRVerejneOznamyOznamTyp", "OznamTyp")
                        .WithMany()
                        .HasForeignKey("OznamTypId");

                    b.Navigation("DruhPodania");

                    b.Navigation("Konanie");

                    b.Navigation("KonanieTyp");

                    b.Navigation("OznamTyp");
                });

            modelBuilder.Entity("IRSlovensko.Models.Konanie", b =>
                {
                    b.Navigation("KonaniaOsoby");
                });
#pragma warning restore 612, 618
        }
    }
}
