// <auto-generated />
using System;
using IRSlovensko.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IRSlovensko.Migrations
{
    [DbContext(typeof(IRDbContext))]
    [Migration("20260416064514_AddVerejneOznamy")]
    partial class AddVerejneOznamy
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("IRSlovensko.Models.Konanie", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DatumPodania")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DatumPoslednejUdalosti")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DatumPovoleniaOddlzenia")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DatumUkonceniaProcesu")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DatumZacatiaKonania")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DatumZacatiaProcesu")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DatumZavedeniaDozornejSpravy")
                        .HasColumnType("datetime2");

                    b.Property<string>("DovodUkonceniaProcesu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("MalyKonkurz")
                        .HasColumnType("bit");

                    b.Property<string>("PoslednaUdalost")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SpisovaZnackaSpravcu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SpisovaZnackaSudu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StavKonania")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SudId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Sudca")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Typ")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TypKonaniaPodlaUzemnejPlatnosti")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TypPrideleniaSpravcu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TypSpravcu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ZnackaSpravcu")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("SudId");

                    b.HasIndex("ZnackaSpravcu");

                    b.ToTable("Konania");
                });

            modelBuilder.Entity("IRSlovensko.Models.KonanieOsoba", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CisloRegistracie")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DatumNarodenia")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Iban")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ico")
                        .HasColumnType("nvarchar(450)");

                    b.Property<long>("IdKonania")
                        .HasColumnType("bigint");

                    b.Property<string>("Krajina")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Meno")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ObchodneMeno")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Obec")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrientacneCislo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PravnaForma")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Priezvisko")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Psc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Register")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RodneCislo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StatneObcianstvo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SupisneCislo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Swift")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TitulPredMenom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TitulZaMenom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Typ")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ulica")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Ico")
                        .HasDatabaseName("IX_KonanieOsoba_Ico");

                    b.HasIndex("IdKonania");

                    b.ToTable("KonaniaOsoby");
                });

            modelBuilder.Entity("IRSlovensko.Models.Spravca", b =>
                {
                    b.Property<string>("Znacka")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("DatumNarodenia")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DatumZapisu")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ico")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Krajina")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Meno")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ObchodneMeno")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Obec")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrientacneCislo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Priezvisko")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Psc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SupisneCislo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TitulPredMenom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TitulZaMenom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ulica")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Znacka");

                    b.ToTable("Spravcovia");
                });

            modelBuilder.Entity("IRSlovensko.Models.Sud", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Nazov")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Sudy");
                });

            modelBuilder.Entity("IRSlovensko.Models.VerejnyOznam", b =>
                {
                    b.Property<long>("OznamId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("DatumVydania")
                        .HasColumnType("datetime2");

                    b.Property<long>("KonanieId")
                        .HasColumnType("bigint");

                    b.Property<string>("KonanieTyp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OznamTyp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SpisovaZnackaSudnehoSpisu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SudKod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SudNazov")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("OznamId");

                    b.HasIndex("KonanieId")
                        .HasDatabaseName("IX_VerejnyOznam_KonanieId");

                    b.ToTable("VerejneOznamy");
                });

            modelBuilder.Entity("IRSlovensko.Models.Konanie", b =>
                {
                    b.HasOne("IRSlovensko.Models.Sud", "Sud")
                        .WithMany()
                        .HasForeignKey("SudId");

                    b.HasOne("IRSlovensko.Models.Spravca", "Spravca")
                        .WithMany()
                        .HasForeignKey("ZnackaSpravcu");

                    b.Navigation("Spravca");

                    b.Navigation("Sud");
                });

            modelBuilder.Entity("IRSlovensko.Models.KonanieOsoba", b =>
                {
                    b.HasOne("IRSlovensko.Models.Konanie", "Konanie")
                        .WithMany("KonaniaOsoby")
                        .HasForeignKey("IdKonania")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Konanie");
                });

            modelBuilder.Entity("IRSlovensko.Models.VerejnyOznam", b =>
                {
                    b.HasOne("IRSlovensko.Models.Konanie", "Konanie")
                        .WithMany()
                        .HasForeignKey("KonanieId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Konanie");
                });

            modelBuilder.Entity("IRSlovensko.Models.Konanie", b =>
                {
                    b.Navigation("KonaniaOsoby");
                });
#pragma warning restore 612, 618
        }
    }
}
