//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReference1
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="datatypes.konanie.verejnost.ru.sk.hp.com", ConfigurationName="ServiceReference1.KonanieServicePort")]
    public interface KonanieServicePort
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference1.vyhladajKonanieResponse1> vyhladajKonanieAsync(ServiceReference1.vyhladajKonanieRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference1.getKonanieDetailPodlaZnackyASuduResponse> getKonanieDetailPodlaZnackyASuduAsync(ServiceReference1.getKonanieDetailPodlaZnackyASuduRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference1.getZoznamSudovResponse> getZoznamSudovAsync(ServiceReference1.getZoznamSudovRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference1.vyhladajPoslednuZmenuOdResponse1> vyhladajPoslednuZmenuOdAsync(ServiceReference1.vyhladajPoslednuZmenuOdRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference1.getKonanieDetailResponse1> getKonanieDetailAsync(ServiceReference1.getKonanieDetailRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference1.getKonaniePreObdobieResponse1> getKonaniePreObdobieAsync(ServiceReference1.getKonaniePreObdobieRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference1.getKonaniePodlaICOResponse1> getKonaniePodlaICOAsync(ServiceReference1.getKonaniePodlaICORequest1 request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="datatypes.konanie.verejnost.ru.sk.hp.com")]
    public partial class vyhladajKonanieRequest
    {
        
        private string queryField;
        
        private int strankaField;
        
        private int vysledkovNaStrankuField;
        
        private TypTriedenia typTriedeniaField;
        
        public vyhladajKonanieRequest()
        {
            this.strankaField = 0;
            this.vysledkovNaStrankuField = 10;
            this.typTriedeniaField = TypTriedenia.DatumPoslednejUdalosti;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Query
        {
            get
            {
                return this.queryField;
            }
            set
            {
                this.queryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        [System.ComponentModel.DefaultValueAttribute(0)]
        public int Stranka
        {
            get
            {
                return this.strankaField;
            }
            set
            {
                this.strankaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        [System.ComponentModel.DefaultValueAttribute(10)]
        public int VysledkovNaStranku
        {
            get
            {
                return this.vysledkovNaStrankuField;
            }
            set
            {
                this.vysledkovNaStrankuField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        [System.ComponentModel.DefaultValueAttribute(TypTriedenia.DatumPoslednejUdalosti)]
        public TypTriedenia TypTriedenia
        {
            get
            {
                return this.typTriedeniaField;
            }
            set
            {
                this.typTriedeniaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="datatypes.konanie.verejnost.ru.sk.hp.com")]
    public enum TypTriedenia
    {
        
        /// <remarks/>
        Relevancia,
        
        /// <remarks/>
        DatumZacatiaKonania,
        
        /// <remarks/>
        DatumPoslednejUdalosti,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="datatypes.konanie.verejnost.ru.sk.hp.com")]
    public partial class PoslednaZmenaNaKonani
    {
        
        private string konanieIdField;
        
        private System.DateTime poslednaZmenaField;
        
        private bool poslednaZmenaFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string KonanieId
        {
            get
            {
                return this.konanieIdField;
            }
            set
            {
                this.konanieIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime PoslednaZmena
        {
            get
            {
                return this.poslednaZmenaField;
            }
            set
            {
                this.poslednaZmenaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PoslednaZmenaSpecified
        {
            get
            {
                return this.poslednaZmenaFieldSpecified;
            }
            set
            {
                this.poslednaZmenaFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="datatypes.konanie.verejnost.ru.sk.hp.com")]
    public partial class Spravca
    {
        
        private string znackaField;
        
        private System.DateTime datumZapisuField;
        
        private bool datumZapisuFieldSpecified;
        
        private string menoField;
        
        private string priezviskoField;
        
        private string titulPredMenomField;
        
        private string titulZaMenomField;
        
        private System.DateTime datumNarodeniaField;
        
        private bool datumNarodeniaFieldSpecified;
        
        private string obchodneMenoField;
        
        private string icoField;
        
        private Adresa adresaField;
        
        private string telefonField;
        
        private string emailField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Znacka
        {
            get
            {
                return this.znackaField;
            }
            set
            {
                this.znackaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=1)]
        public System.DateTime DatumZapisu
        {
            get
            {
                return this.datumZapisuField;
            }
            set
            {
                this.datumZapisuField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DatumZapisuSpecified
        {
            get
            {
                return this.datumZapisuFieldSpecified;
            }
            set
            {
                this.datumZapisuFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Meno
        {
            get
            {
                return this.menoField;
            }
            set
            {
                this.menoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Priezvisko
        {
            get
            {
                return this.priezviskoField;
            }
            set
            {
                this.priezviskoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string TitulPredMenom
        {
            get
            {
                return this.titulPredMenomField;
            }
            set
            {
                this.titulPredMenomField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string TitulZaMenom
        {
            get
            {
                return this.titulZaMenomField;
            }
            set
            {
                this.titulZaMenomField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=6)]
        public System.DateTime DatumNarodenia
        {
            get
            {
                return this.datumNarodeniaField;
            }
            set
            {
                this.datumNarodeniaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DatumNarodeniaSpecified
        {
            get
            {
                return this.datumNarodeniaFieldSpecified;
            }
            set
            {
                this.datumNarodeniaFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string ObchodneMeno
        {
            get
            {
                return this.obchodneMenoField;
            }
            set
            {
                this.obchodneMenoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string Ico
        {
            get
            {
                return this.icoField;
            }
            set
            {
                this.icoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public Adresa Adresa
        {
            get
            {
                return this.adresaField;
            }
            set
            {
                this.adresaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string Telefon
        {
            get
            {
                return this.telefonField;
            }
            set
            {
                this.telefonField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string Email
        {
            get
            {
                return this.emailField;
            }
            set
            {
                this.emailField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="datatypes.konanie.verejnost.ru.sk.hp.com")]
    public partial class Adresa
    {
        
        private string ulicaField;
        
        private string supisneCisloField;
        
        private string orientacneCisloField;
        
        private string obecField;
        
        private string pscField;
        
        private string krajinaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Ulica
        {
            get
            {
                return this.ulicaField;
            }
            set
            {
                this.ulicaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string SupisneCislo
        {
            get
            {
                return this.supisneCisloField;
            }
            set
            {
                this.supisneCisloField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string OrientacneCislo
        {
            get
            {
                return this.orientacneCisloField;
            }
            set
            {
                this.orientacneCisloField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Obec
        {
            get
            {
                return this.obecField;
            }
            set
            {
                this.obecField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Psc
        {
            get
            {
                return this.pscField;
            }
            set
            {
                this.pscField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Krajina
        {
            get
            {
                return this.krajinaField;
            }
            set
            {
                this.krajinaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="datatypes.konanie.verejnost.ru.sk.hp.com")]
    public partial class Sud
    {
        
        private string idField;
        
        private string nazovField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string nazov
        {
            get
            {
                return this.nazovField;
            }
            set
            {
                this.nazovField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="datatypes.konanie.verejnost.ru.sk.hp.com")]
    public partial class BankovyUcet
    {
        
        private string ibanField;
        
        private string swiftField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Iban
        {
            get
            {
                return this.ibanField;
            }
            set
            {
                this.ibanField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Swift
        {
            get
            {
                return this.swiftField;
            }
            set
            {
                this.swiftField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PravnickaOsoba))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(FyzickaOsobaPodnikatel))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(FyzickaOsoba))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="datatypes.konanie.verejnost.ru.sk.hp.com")]
    public partial class Osoba
    {
        
        private Adresa adresaField;
        
        private string telefonField;
        
        private string emailField;
        
        private BankovyUcet bankovyUcetField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public Adresa Adresa
        {
            get
            {
                return this.adresaField;
            }
            set
            {
                this.adresaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Telefon
        {
            get
            {
                return this.telefonField;
            }
            set
            {
                this.telefonField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Email
        {
            get
            {
                return this.emailField;
            }
            set
            {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public BankovyUcet BankovyUcet
        {
            get
            {
                return this.bankovyUcetField;
            }
            set
            {
                this.bankovyUcetField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="datatypes.konanie.verejnost.ru.sk.hp.com")]
    public partial class PravnickaOsoba : Osoba
    {
        
        private string obchodneMenoField;
        
        private string icoField;
        
        private string pravnaFormaField;
        
        private string registerField;
        
        private string cisloRegistracieField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ObchodneMeno
        {
            get
            {
                return this.obchodneMenoField;
            }
            set
            {
                this.obchodneMenoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Ico
        {
            get
            {
                return this.icoField;
            }
            set
            {
                this.icoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string PravnaForma
        {
            get
            {
                return this.pravnaFormaField;
            }
            set
            {
                this.pravnaFormaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Register
        {
            get
            {
                return this.registerField;
            }
            set
            {
                this.registerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string CisloRegistracie
        {
            get
            {
                return this.cisloRegistracieField;
            }
            set
            {
                this.cisloRegistracieField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="datatypes.konanie.verejnost.ru.sk.hp.com")]
    public partial class FyzickaOsobaPodnikatel : Osoba
    {
        
        private string obchodneMenoField;
        
        private string menoField;
        
        private string priezviskoField;
        
        private string titulPredMenomField;
        
        private string titulZaMenomField;
        
        private string icoField;
        
        private string registerField;
        
        private string cisloRegistracieField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ObchodneMeno
        {
            get
            {
                return this.obchodneMenoField;
            }
            set
            {
                this.obchodneMenoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Meno
        {
            get
            {
                return this.menoField;
            }
            set
            {
                this.menoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Priezvisko
        {
            get
            {
                return this.priezviskoField;
            }
            set
            {
                this.priezviskoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string TitulPredMenom
        {
            get
            {
                return this.titulPredMenomField;
            }
            set
            {
                this.titulPredMenomField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string TitulZaMenom
        {
            get
            {
                return this.titulZaMenomField;
            }
            set
            {
                this.titulZaMenomField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Ico
        {
            get
            {
                return this.icoField;
            }
            set
            {
                this.icoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Register
        {
            get
            {
                return this.registerField;
            }
            set
            {
                this.registerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string CisloRegistracie
        {
            get
            {
                return this.cisloRegistracieField;
            }
            set
            {
                this.cisloRegistracieField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="datatypes.konanie.verejnost.ru.sk.hp.com")]
    public partial class FyzickaOsoba : Osoba
    {
        
        private string menoField;
        
        private string priezviskoField;
        
        private string titulPredMenomField;
        
        private string titulZaMenomField;
        
        private string rodneCisloField;
        
        private System.DateTime datumNarodeniaField;
        
        private string statneObcianstvoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Meno
        {
            get
            {
                return this.menoField;
            }
            set
            {
                this.menoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Priezvisko
        {
            get
            {
                return this.priezviskoField;
            }
            set
            {
                this.priezviskoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string TitulPredMenom
        {
            get
            {
                return this.titulPredMenomField;
            }
            set
            {
                this.titulPredMenomField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string TitulZaMenom
        {
            get
            {
                return this.titulZaMenomField;
            }
            set
            {
                this.titulZaMenomField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string RodneCislo
        {
            get
            {
                return this.rodneCisloField;
            }
            set
            {
                this.rodneCisloField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=5)]
        public System.DateTime DatumNarodenia
        {
            get
            {
                return this.datumNarodeniaField;
            }
            set
            {
                this.datumNarodeniaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string StatneObcianstvo
        {
            get
            {
                return this.statneObcianstvoField;
            }
            set
            {
                this.statneObcianstvoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(VPR))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Likvidacia))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(OddlzenieSplatkovyKalendar))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(OddlzenieKonkurz))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Restrukturalizacia))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Konkurz))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="datatypes.konanie.verejnost.ru.sk.hp.com")]
    public partial class Konanie
    {
        
        private long idField;
        
        private string spisovaZnackaSpravcuField;
        
        private string spisovaZnackaSuduField;
        
        private KonanieTyp typField;
        
        private bool typFieldSpecified;
        
        private Osoba[] navrhovatelField;
        
        private Osoba dlznikField;
        
        private Sud sudField;
        
        private string sudcaField;
        
        private Spravca spravcaField;
        
        private System.DateTime datumZacatiaKonaniaField;
        
        private System.DateTime datumZacatiaProcesuField;
        
        private TypSpravcuNaKonani typSpravcuField;
        
        private bool typSpravcuFieldSpecified;
        
        private TypPrideleniaSpravcu typPrideleniaSpravcuField;
        
        private bool typPrideleniaSpravcuFieldSpecified;
        
        private string typKonaniaPodlaUzemnejPlatnostiField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long Id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string SpisovaZnackaSpravcu
        {
            get
            {
                return this.spisovaZnackaSpravcuField;
            }
            set
            {
                this.spisovaZnackaSpravcuField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string SpisovaZnackaSudu
        {
            get
            {
                return this.spisovaZnackaSuduField;
            }
            set
            {
                this.spisovaZnackaSuduField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public KonanieTyp Typ
        {
            get
            {
                return this.typField;
            }
            set
            {
                this.typField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TypSpecified
        {
            get
            {
                return this.typFieldSpecified;
            }
            set
            {
                this.typFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Navrhovatel", Order=4)]
        public Osoba[] Navrhovatel
        {
            get
            {
                return this.navrhovatelField;
            }
            set
            {
                this.navrhovatelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public Osoba Dlznik
        {
            get
            {
                return this.dlznikField;
            }
            set
            {
                this.dlznikField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public Sud Sud
        {
            get
            {
                return this.sudField;
            }
            set
            {
                this.sudField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string Sudca
        {
            get
            {
                return this.sudcaField;
            }
            set
            {
                this.sudcaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public Spravca Spravca
        {
            get
            {
                return this.spravcaField;
            }
            set
            {
                this.spravcaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=9)]
        public System.DateTime DatumZacatiaKonania
        {
            get
            {
                return this.datumZacatiaKonaniaField;
            }
            set
            {
                this.datumZacatiaKonaniaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=10)]
        public System.DateTime DatumZacatiaProcesu
        {
            get
            {
                return this.datumZacatiaProcesuField;
            }
            set
            {
                this.datumZacatiaProcesuField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public TypSpravcuNaKonani TypSpravcu
        {
            get
            {
                return this.typSpravcuField;
            }
            set
            {
                this.typSpravcuField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TypSpravcuSpecified
        {
            get
            {
                return this.typSpravcuFieldSpecified;
            }
            set
            {
                this.typSpravcuFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public TypPrideleniaSpravcu TypPrideleniaSpravcu
        {
            get
            {
                return this.typPrideleniaSpravcuField;
            }
            set
            {
                this.typPrideleniaSpravcuField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TypPrideleniaSpravcuSpecified
        {
            get
            {
                return this.typPrideleniaSpravcuFieldSpecified;
            }
            set
            {
                this.typPrideleniaSpravcuFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string TypKonaniaPodlaUzemnejPlatnosti
        {
            get
            {
                return this.typKonaniaPodlaUzemnejPlatnostiField;
            }
            set
            {
                this.typKonaniaPodlaUzemnejPlatnostiField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="datatypes.konanie.verejnost.ru.sk.hp.com")]
    public enum KonanieTyp
    {
        
        /// <remarks/>
        RESTRUKTURALIZACIA,
        
        /// <remarks/>
        KONKURZ,
        
        /// <remarks/>
        MALYKONKURZ,
        
        /// <remarks/>
        ODDLZENIE_KONKURZ,
        
        /// <remarks/>
        ODDLZENIE_SPLATKOVY_KALENDAR,
        
        /// <remarks/>
        LIKVIDACIA,
        
        /// <remarks/>
        VPR,
        
        /// <remarks/>
        INE,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="datatypes.konanie.verejnost.ru.sk.hp.com")]
    public enum TypSpravcuNaKonani
    {
        
        /// <remarks/>
        RIADNY,
        
        /// <remarks/>
        PREDBEZNY,
        
        /// <remarks/>
        DOZORNY,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="datatypes.konanie.verejnost.ru.sk.hp.com")]
    public enum TypPrideleniaSpravcu
    {
        
        /// <remarks/>
        GENEROVANY,
        
        /// <remarks/>
        VYMENOVANY,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="datatypes.konanie.verejnost.ru.sk.hp.com")]
    public partial class VPR : Konanie
    {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="datatypes.konanie.verejnost.ru.sk.hp.com")]
    public partial class Likvidacia : Konanie
    {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="datatypes.konanie.verejnost.ru.sk.hp.com")]
    public partial class OddlzenieSplatkovyKalendar : Konanie
    {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="datatypes.konanie.verejnost.ru.sk.hp.com")]
    public partial class OddlzenieKonkurz : Konanie
    {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="datatypes.konanie.verejnost.ru.sk.hp.com")]
    public partial class Restrukturalizacia : Konanie
    {
        
        private System.DateTime datumZavedeniaDozornejSpravyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=0)]
        public System.DateTime DatumZavedeniaDozornejSpravy
        {
            get
            {
                return this.datumZavedeniaDozornejSpravyField;
            }
            set
            {
                this.datumZavedeniaDozornejSpravyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="datatypes.konanie.verejnost.ru.sk.hp.com")]
    public partial class Konkurz : Konanie
    {
        
        private bool malyKonkurzField;
        
        private System.DateTime datumPovoleniaOddlzeniaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool MalyKonkurz
        {
            get
            {
                return this.malyKonkurzField;
            }
            set
            {
                this.malyKonkurzField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=1)]
        public System.DateTime DatumPovoleniaOddlzenia
        {
            get
            {
                return this.datumPovoleniaOddlzeniaField;
            }
            set
            {
                this.datumPovoleniaOddlzeniaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="datatypes.konanie.verejnost.ru.sk.hp.com")]
    public partial class KonanieInfo
    {
        
        private long idField;
        
        private string spisovaZnackaSpravcuField;
        
        private string spisovaZnackaSuduField;
        
        private KonanieTyp typField;
        
        private bool typFieldSpecified;
        
        private System.DateTime datumZacatiaKonaniaField;
        
        private bool datumZacatiaKonaniaFieldSpecified;
        
        private System.DateTime datumZacatiaProcesuField;
        
        private bool datumZacatiaProcesuFieldSpecified;
        
        private System.DateTime datumUkonceniaProcesuField;
        
        private bool datumUkonceniaProcesuFieldSpecified;
        
        private string dovodUkonceniaProcesuField;
        
        private System.DateTime datumPodaniaField;
        
        private bool datumPodaniaFieldSpecified;
        
        private string dlznikField;
        
        private string dlznikIcoField;
        
        private System.DateTime dlznikDatumNarodeniaField;
        
        private bool dlznikDatumNarodeniaFieldSpecified;
        
        private string poslednaUdalostField;
        
        private System.DateTime datumPoslednejUdalostiField;
        
        private bool datumPoslednejUdalostiFieldSpecified;
        
        private string sudField;
        
        private string sudNazovField;
        
        private string spravcaField;
        
        private TypSpravcuNaKonani typSpravcuField;
        
        private bool typSpravcuFieldSpecified;
        
        private TypPrideleniaSpravcu typPrideleniaSpravcuField;
        
        private bool typPrideleniaSpravcuFieldSpecified;
        
        private string stavKonaniaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long Id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string SpisovaZnackaSpravcu
        {
            get
            {
                return this.spisovaZnackaSpravcuField;
            }
            set
            {
                this.spisovaZnackaSpravcuField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string SpisovaZnackaSudu
        {
            get
            {
                return this.spisovaZnackaSuduField;
            }
            set
            {
                this.spisovaZnackaSuduField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public KonanieTyp Typ
        {
            get
            {
                return this.typField;
            }
            set
            {
                this.typField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TypSpecified
        {
            get
            {
                return this.typFieldSpecified;
            }
            set
            {
                this.typFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=4)]
        public System.DateTime DatumZacatiaKonania
        {
            get
            {
                return this.datumZacatiaKonaniaField;
            }
            set
            {
                this.datumZacatiaKonaniaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DatumZacatiaKonaniaSpecified
        {
            get
            {
                return this.datumZacatiaKonaniaFieldSpecified;
            }
            set
            {
                this.datumZacatiaKonaniaFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=5)]
        public System.DateTime DatumZacatiaProcesu
        {
            get
            {
                return this.datumZacatiaProcesuField;
            }
            set
            {
                this.datumZacatiaProcesuField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DatumZacatiaProcesuSpecified
        {
            get
            {
                return this.datumZacatiaProcesuFieldSpecified;
            }
            set
            {
                this.datumZacatiaProcesuFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=6)]
        public System.DateTime DatumUkonceniaProcesu
        {
            get
            {
                return this.datumUkonceniaProcesuField;
            }
            set
            {
                this.datumUkonceniaProcesuField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DatumUkonceniaProcesuSpecified
        {
            get
            {
                return this.datumUkonceniaProcesuFieldSpecified;
            }
            set
            {
                this.datumUkonceniaProcesuFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string DovodUkonceniaProcesu
        {
            get
            {
                return this.dovodUkonceniaProcesuField;
            }
            set
            {
                this.dovodUkonceniaProcesuField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=8)]
        public System.DateTime DatumPodania
        {
            get
            {
                return this.datumPodaniaField;
            }
            set
            {
                this.datumPodaniaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DatumPodaniaSpecified
        {
            get
            {
                return this.datumPodaniaFieldSpecified;
            }
            set
            {
                this.datumPodaniaFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string Dlznik
        {
            get
            {
                return this.dlznikField;
            }
            set
            {
                this.dlznikField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string DlznikIco
        {
            get
            {
                return this.dlznikIcoField;
            }
            set
            {
                this.dlznikIcoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=11)]
        public System.DateTime DlznikDatumNarodenia
        {
            get
            {
                return this.dlznikDatumNarodeniaField;
            }
            set
            {
                this.dlznikDatumNarodeniaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DlznikDatumNarodeniaSpecified
        {
            get
            {
                return this.dlznikDatumNarodeniaFieldSpecified;
            }
            set
            {
                this.dlznikDatumNarodeniaFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string PoslednaUdalost
        {
            get
            {
                return this.poslednaUdalostField;
            }
            set
            {
                this.poslednaUdalostField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=13)]
        public System.DateTime DatumPoslednejUdalosti
        {
            get
            {
                return this.datumPoslednejUdalostiField;
            }
            set
            {
                this.datumPoslednejUdalostiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DatumPoslednejUdalostiSpecified
        {
            get
            {
                return this.datumPoslednejUdalostiFieldSpecified;
            }
            set
            {
                this.datumPoslednejUdalostiFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string Sud
        {
            get
            {
                return this.sudField;
            }
            set
            {
                this.sudField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string SudNazov
        {
            get
            {
                return this.sudNazovField;
            }
            set
            {
                this.sudNazovField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string Spravca
        {
            get
            {
                return this.spravcaField;
            }
            set
            {
                this.spravcaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public TypSpravcuNaKonani TypSpravcu
        {
            get
            {
                return this.typSpravcuField;
            }
            set
            {
                this.typSpravcuField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TypSpravcuSpecified
        {
            get
            {
                return this.typSpravcuFieldSpecified;
            }
            set
            {
                this.typSpravcuFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public TypPrideleniaSpravcu TypPrideleniaSpravcu
        {
            get
            {
                return this.typPrideleniaSpravcuField;
            }
            set
            {
                this.typPrideleniaSpravcuField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TypPrideleniaSpravcuSpecified
        {
            get
            {
                return this.typPrideleniaSpravcuFieldSpecified;
            }
            set
            {
                this.typPrideleniaSpravcuFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public string StavKonania
        {
            get
            {
                return this.stavKonaniaField;
            }
            set
            {
                this.stavKonaniaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="datatypes.konanie.verejnost.ru.sk.hp.com")]
    public partial class vyhladajKonanieResponse
    {
        
        private KonanieInfo[] konanieInfoListField;
        
        private long vysledkovCelkomField;
        
        public vyhladajKonanieResponse()
        {
            this.vysledkovCelkomField = ((long)(0));
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public KonanieInfo[] KonanieInfoList
        {
            get
            {
                return this.konanieInfoListField;
            }
            set
            {
                this.konanieInfoListField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public long VysledkovCelkom
        {
            get
            {
                return this.vysledkovCelkomField;
            }
            set
            {
                this.vysledkovCelkomField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class vyhladajKonanieRequest1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="datatypes.konanie.verejnost.ru.sk.hp.com", Order=0)]
        public ServiceReference1.vyhladajKonanieRequest vyhladajKonanieRequest;
        
        public vyhladajKonanieRequest1()
        {
        }
        
        public vyhladajKonanieRequest1(ServiceReference1.vyhladajKonanieRequest vyhladajKonanieRequest)
        {
            this.vyhladajKonanieRequest = vyhladajKonanieRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class vyhladajKonanieResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="datatypes.konanie.verejnost.ru.sk.hp.com", Order=0)]
        public ServiceReference1.vyhladajKonanieResponse vyhladajKonanieResponse;
        
        public vyhladajKonanieResponse1()
        {
        }
        
        public vyhladajKonanieResponse1(ServiceReference1.vyhladajKonanieResponse vyhladajKonanieResponse)
        {
            this.vyhladajKonanieResponse = vyhladajKonanieResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="datatypes.konanie.verejnost.ru.sk.hp.com")]
    public partial class getKonanieDetailPodlaZnackyASuduRequest
    {
        
        private string konanieZnackaField;
        
        private string konanieSudField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string KonanieZnacka
        {
            get
            {
                return this.konanieZnackaField;
            }
            set
            {
                this.konanieZnackaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string KonanieSud
        {
            get
            {
                return this.konanieSudField;
            }
            set
            {
                this.konanieSudField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getKonanieDetailPodlaZnackyASuduRequest1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="datatypes.konanie.verejnost.ru.sk.hp.com", Order=0)]
        public ServiceReference1.getKonanieDetailPodlaZnackyASuduRequest getKonanieDetailPodlaZnackyASuduRequest;
        
        public getKonanieDetailPodlaZnackyASuduRequest1()
        {
        }
        
        public getKonanieDetailPodlaZnackyASuduRequest1(ServiceReference1.getKonanieDetailPodlaZnackyASuduRequest getKonanieDetailPodlaZnackyASuduRequest)
        {
            this.getKonanieDetailPodlaZnackyASuduRequest = getKonanieDetailPodlaZnackyASuduRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getKonanieDetailPodlaZnackyASuduResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getKonanieDetailPodlaZnackyASuduResponse", Namespace="datatypes.konanie.verejnost.ru.sk.hp.com", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public ServiceReference1.Konanie[] getKonanieDetailPodlaZnackyASuduResponse1;
        
        public getKonanieDetailPodlaZnackyASuduResponse()
        {
        }
        
        public getKonanieDetailPodlaZnackyASuduResponse(ServiceReference1.Konanie[] getKonanieDetailPodlaZnackyASuduResponse1)
        {
            this.getKonanieDetailPodlaZnackyASuduResponse1 = getKonanieDetailPodlaZnackyASuduResponse1;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="datatypes.konanie.verejnost.ru.sk.hp.com")]
    public partial class getZoznamSudovRequest
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getZoznamSudovRequest1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="datatypes.konanie.verejnost.ru.sk.hp.com", Order=0)]
        public ServiceReference1.getZoznamSudovRequest getZoznamSudovRequest;
        
        public getZoznamSudovRequest1()
        {
        }
        
        public getZoznamSudovRequest1(ServiceReference1.getZoznamSudovRequest getZoznamSudovRequest)
        {
            this.getZoznamSudovRequest = getZoznamSudovRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getZoznamSudovResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getZoznamSudovResponse", Namespace="datatypes.konanie.verejnost.ru.sk.hp.com", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public ServiceReference1.Sud[] getZoznamSudovResponse1;
        
        public getZoznamSudovResponse()
        {
        }
        
        public getZoznamSudovResponse(ServiceReference1.Sud[] getZoznamSudovResponse1)
        {
            this.getZoznamSudovResponse1 = getZoznamSudovResponse1;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="datatypes.konanie.verejnost.ru.sk.hp.com")]
    public partial class vyhladajPoslednuZmenuOdRequest
    {
        
        private System.DateTime zmenyOdField;
        
        private bool zmenyOdFieldSpecified;
        
        private int maximalnyPocetVysledkovField;
        
        public vyhladajPoslednuZmenuOdRequest()
        {
            this.maximalnyPocetVysledkovField = 100;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.DateTime ZmenyOd
        {
            get
            {
                return this.zmenyOdField;
            }
            set
            {
                this.zmenyOdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ZmenyOdSpecified
        {
            get
            {
                return this.zmenyOdFieldSpecified;
            }
            set
            {
                this.zmenyOdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        [System.ComponentModel.DefaultValueAttribute(100)]
        public int MaximalnyPocetVysledkov
        {
            get
            {
                return this.maximalnyPocetVysledkovField;
            }
            set
            {
                this.maximalnyPocetVysledkovField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="datatypes.konanie.verejnost.ru.sk.hp.com")]
    public partial class vyhladajPoslednuZmenuOdResponse
    {
        
        private PoslednaZmenaNaKonani[] poslednaZmenaNaKonaniListField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public PoslednaZmenaNaKonani[] PoslednaZmenaNaKonaniList
        {
            get
            {
                return this.poslednaZmenaNaKonaniListField;
            }
            set
            {
                this.poslednaZmenaNaKonaniListField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class vyhladajPoslednuZmenuOdRequest1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="datatypes.konanie.verejnost.ru.sk.hp.com", Order=0)]
        public ServiceReference1.vyhladajPoslednuZmenuOdRequest vyhladajPoslednuZmenuOdRequest;
        
        public vyhladajPoslednuZmenuOdRequest1()
        {
        }
        
        public vyhladajPoslednuZmenuOdRequest1(ServiceReference1.vyhladajPoslednuZmenuOdRequest vyhladajPoslednuZmenuOdRequest)
        {
            this.vyhladajPoslednuZmenuOdRequest = vyhladajPoslednuZmenuOdRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class vyhladajPoslednuZmenuOdResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="datatypes.konanie.verejnost.ru.sk.hp.com", Order=0)]
        public ServiceReference1.vyhladajPoslednuZmenuOdResponse vyhladajPoslednuZmenuOdResponse;
        
        public vyhladajPoslednuZmenuOdResponse1()
        {
        }
        
        public vyhladajPoslednuZmenuOdResponse1(ServiceReference1.vyhladajPoslednuZmenuOdResponse vyhladajPoslednuZmenuOdResponse)
        {
            this.vyhladajPoslednuZmenuOdResponse = vyhladajPoslednuZmenuOdResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="datatypes.konanie.verejnost.ru.sk.hp.com")]
    public partial class getKonanieDetailRequest
    {
        
        private string konanieIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string KonanieId
        {
            get
            {
                return this.konanieIdField;
            }
            set
            {
                this.konanieIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="datatypes.konanie.verejnost.ru.sk.hp.com")]
    public partial class getKonanieDetailResponse
    {
        
        private Konanie konanieField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public Konanie Konanie
        {
            get
            {
                return this.konanieField;
            }
            set
            {
                this.konanieField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getKonanieDetailRequest1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="datatypes.konanie.verejnost.ru.sk.hp.com", Order=0)]
        public ServiceReference1.getKonanieDetailRequest getKonanieDetailRequest;
        
        public getKonanieDetailRequest1()
        {
        }
        
        public getKonanieDetailRequest1(ServiceReference1.getKonanieDetailRequest getKonanieDetailRequest)
        {
            this.getKonanieDetailRequest = getKonanieDetailRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getKonanieDetailResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="datatypes.konanie.verejnost.ru.sk.hp.com", Order=0)]
        public ServiceReference1.getKonanieDetailResponse getKonanieDetailResponse;
        
        public getKonanieDetailResponse1()
        {
        }
        
        public getKonanieDetailResponse1(ServiceReference1.getKonanieDetailResponse getKonanieDetailResponse)
        {
            this.getKonanieDetailResponse = getKonanieDetailResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="datatypes.konanie.verejnost.ru.sk.hp.com")]
    public partial class getKonaniePreObdobieRequest
    {
        
        private System.DateTime datumOdField;
        
        private System.DateTime datumDoField;
        
        private int strankaField;
        
        private int vysledkovNaStrankuField;
        
        public getKonaniePreObdobieRequest()
        {
            this.strankaField = 0;
            this.vysledkovNaStrankuField = 10;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=0)]
        public System.DateTime DatumOd
        {
            get
            {
                return this.datumOdField;
            }
            set
            {
                this.datumOdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=1)]
        public System.DateTime DatumDo
        {
            get
            {
                return this.datumDoField;
            }
            set
            {
                this.datumDoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        [System.ComponentModel.DefaultValueAttribute(0)]
        public int Stranka
        {
            get
            {
                return this.strankaField;
            }
            set
            {
                this.strankaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        [System.ComponentModel.DefaultValueAttribute(10)]
        public int VysledkovNaStranku
        {
            get
            {
                return this.vysledkovNaStrankuField;
            }
            set
            {
                this.vysledkovNaStrankuField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="datatypes.konanie.verejnost.ru.sk.hp.com")]
    public partial class getKonaniePreObdobieResponse
    {
        
        private KonanieInfo[] konanieInfoListField;
        
        private long vysledkovCelkomField;
        
        public getKonaniePreObdobieResponse()
        {
            this.vysledkovCelkomField = ((long)(0));
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public KonanieInfo[] KonanieInfoList
        {
            get
            {
                return this.konanieInfoListField;
            }
            set
            {
                this.konanieInfoListField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public long VysledkovCelkom
        {
            get
            {
                return this.vysledkovCelkomField;
            }
            set
            {
                this.vysledkovCelkomField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getKonaniePreObdobieRequest1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="datatypes.konanie.verejnost.ru.sk.hp.com", Order=0)]
        public ServiceReference1.getKonaniePreObdobieRequest getKonaniePreObdobieRequest;
        
        public getKonaniePreObdobieRequest1()
        {
        }
        
        public getKonaniePreObdobieRequest1(ServiceReference1.getKonaniePreObdobieRequest getKonaniePreObdobieRequest)
        {
            this.getKonaniePreObdobieRequest = getKonaniePreObdobieRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getKonaniePreObdobieResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="datatypes.konanie.verejnost.ru.sk.hp.com", Order=0)]
        public ServiceReference1.getKonaniePreObdobieResponse getKonaniePreObdobieResponse;
        
        public getKonaniePreObdobieResponse1()
        {
        }
        
        public getKonaniePreObdobieResponse1(ServiceReference1.getKonaniePreObdobieResponse getKonaniePreObdobieResponse)
        {
            this.getKonaniePreObdobieResponse = getKonaniePreObdobieResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="datatypes.konanie.verejnost.ru.sk.hp.com")]
    public partial class getKonaniePodlaICORequest
    {
        
        private string icoField;
        
        private int strankaField;
        
        private int vysledkovNaStrankuField;
        
        private TypTriedenia typTriedeniaField;
        
        public getKonaniePodlaICORequest()
        {
            this.strankaField = 0;
            this.vysledkovNaStrankuField = 10;
            this.typTriedeniaField = TypTriedenia.DatumPoslednejUdalosti;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Ico
        {
            get
            {
                return this.icoField;
            }
            set
            {
                this.icoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        [System.ComponentModel.DefaultValueAttribute(0)]
        public int Stranka
        {
            get
            {
                return this.strankaField;
            }
            set
            {
                this.strankaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        [System.ComponentModel.DefaultValueAttribute(10)]
        public int VysledkovNaStranku
        {
            get
            {
                return this.vysledkovNaStrankuField;
            }
            set
            {
                this.vysledkovNaStrankuField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        [System.ComponentModel.DefaultValueAttribute(TypTriedenia.DatumPoslednejUdalosti)]
        public TypTriedenia TypTriedenia
        {
            get
            {
                return this.typTriedeniaField;
            }
            set
            {
                this.typTriedeniaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="datatypes.konanie.verejnost.ru.sk.hp.com")]
    public partial class getKonaniePodlaICOResponse
    {
        
        private KonanieInfo[] konanieInfoListField;
        
        private long vysledkovCelkomField;
        
        public getKonaniePodlaICOResponse()
        {
            this.vysledkovCelkomField = ((long)(0));
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public KonanieInfo[] KonanieInfoList
        {
            get
            {
                return this.konanieInfoListField;
            }
            set
            {
                this.konanieInfoListField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public long VysledkovCelkom
        {
            get
            {
                return this.vysledkovCelkomField;
            }
            set
            {
                this.vysledkovCelkomField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getKonaniePodlaICORequest1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="datatypes.konanie.verejnost.ru.sk.hp.com", Order=0)]
        public ServiceReference1.getKonaniePodlaICORequest getKonaniePodlaICORequest;
        
        public getKonaniePodlaICORequest1()
        {
        }
        
        public getKonaniePodlaICORequest1(ServiceReference1.getKonaniePodlaICORequest getKonaniePodlaICORequest)
        {
            this.getKonaniePodlaICORequest = getKonaniePodlaICORequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getKonaniePodlaICOResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="datatypes.konanie.verejnost.ru.sk.hp.com", Order=0)]
        public ServiceReference1.getKonaniePodlaICOResponse getKonaniePodlaICOResponse;
        
        public getKonaniePodlaICOResponse1()
        {
        }
        
        public getKonaniePodlaICOResponse1(ServiceReference1.getKonaniePodlaICOResponse getKonaniePodlaICOResponse)
        {
            this.getKonaniePodlaICOResponse = getKonaniePodlaICOResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface KonanieServicePortChannel : ServiceReference1.KonanieServicePort, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class KonanieServicePortClient : System.ServiceModel.ClientBase<ServiceReference1.KonanieServicePort>, ServiceReference1.KonanieServicePort
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public KonanieServicePortClient() : 
                base(KonanieServicePortClient.GetDefaultBinding(), KonanieServicePortClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.KonanieServicePortSoap11.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public KonanieServicePortClient(EndpointConfiguration endpointConfiguration) : 
                base(KonanieServicePortClient.GetBindingForEndpoint(endpointConfiguration), KonanieServicePortClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public KonanieServicePortClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(KonanieServicePortClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public KonanieServicePortClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(KonanieServicePortClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public KonanieServicePortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.vyhladajKonanieResponse1> ServiceReference1.KonanieServicePort.vyhladajKonanieAsync(ServiceReference1.vyhladajKonanieRequest1 request)
        {
            return base.Channel.vyhladajKonanieAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.vyhladajKonanieResponse1> vyhladajKonanieAsync(ServiceReference1.vyhladajKonanieRequest vyhladajKonanieRequest)
        {
            ServiceReference1.vyhladajKonanieRequest1 inValue = new ServiceReference1.vyhladajKonanieRequest1();
            inValue.vyhladajKonanieRequest = vyhladajKonanieRequest;
            return ((ServiceReference1.KonanieServicePort)(this)).vyhladajKonanieAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.getKonanieDetailPodlaZnackyASuduResponse> ServiceReference1.KonanieServicePort.getKonanieDetailPodlaZnackyASuduAsync(ServiceReference1.getKonanieDetailPodlaZnackyASuduRequest1 request)
        {
            return base.Channel.getKonanieDetailPodlaZnackyASuduAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.getKonanieDetailPodlaZnackyASuduResponse> getKonanieDetailPodlaZnackyASuduAsync(ServiceReference1.getKonanieDetailPodlaZnackyASuduRequest getKonanieDetailPodlaZnackyASuduRequest)
        {
            ServiceReference1.getKonanieDetailPodlaZnackyASuduRequest1 inValue = new ServiceReference1.getKonanieDetailPodlaZnackyASuduRequest1();
            inValue.getKonanieDetailPodlaZnackyASuduRequest = getKonanieDetailPodlaZnackyASuduRequest;
            return ((ServiceReference1.KonanieServicePort)(this)).getKonanieDetailPodlaZnackyASuduAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.getZoznamSudovResponse> ServiceReference1.KonanieServicePort.getZoznamSudovAsync(ServiceReference1.getZoznamSudovRequest1 request)
        {
            return base.Channel.getZoznamSudovAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.getZoznamSudovResponse> getZoznamSudovAsync(ServiceReference1.getZoznamSudovRequest getZoznamSudovRequest)
        {
            ServiceReference1.getZoznamSudovRequest1 inValue = new ServiceReference1.getZoznamSudovRequest1();
            inValue.getZoznamSudovRequest = getZoznamSudovRequest;
            return ((ServiceReference1.KonanieServicePort)(this)).getZoznamSudovAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.vyhladajPoslednuZmenuOdResponse1> ServiceReference1.KonanieServicePort.vyhladajPoslednuZmenuOdAsync(ServiceReference1.vyhladajPoslednuZmenuOdRequest1 request)
        {
            return base.Channel.vyhladajPoslednuZmenuOdAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.vyhladajPoslednuZmenuOdResponse1> vyhladajPoslednuZmenuOdAsync(ServiceReference1.vyhladajPoslednuZmenuOdRequest vyhladajPoslednuZmenuOdRequest)
        {
            ServiceReference1.vyhladajPoslednuZmenuOdRequest1 inValue = new ServiceReference1.vyhladajPoslednuZmenuOdRequest1();
            inValue.vyhladajPoslednuZmenuOdRequest = vyhladajPoslednuZmenuOdRequest;
            return ((ServiceReference1.KonanieServicePort)(this)).vyhladajPoslednuZmenuOdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.getKonanieDetailResponse1> ServiceReference1.KonanieServicePort.getKonanieDetailAsync(ServiceReference1.getKonanieDetailRequest1 request)
        {
            return base.Channel.getKonanieDetailAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.getKonanieDetailResponse1> getKonanieDetailAsync(ServiceReference1.getKonanieDetailRequest getKonanieDetailRequest)
        {
            ServiceReference1.getKonanieDetailRequest1 inValue = new ServiceReference1.getKonanieDetailRequest1();
            inValue.getKonanieDetailRequest = getKonanieDetailRequest;
            return ((ServiceReference1.KonanieServicePort)(this)).getKonanieDetailAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.getKonaniePreObdobieResponse1> ServiceReference1.KonanieServicePort.getKonaniePreObdobieAsync(ServiceReference1.getKonaniePreObdobieRequest1 request)
        {
            return base.Channel.getKonaniePreObdobieAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.getKonaniePreObdobieResponse1> getKonaniePreObdobieAsync(ServiceReference1.getKonaniePreObdobieRequest getKonaniePreObdobieRequest)
        {
            ServiceReference1.getKonaniePreObdobieRequest1 inValue = new ServiceReference1.getKonaniePreObdobieRequest1();
            inValue.getKonaniePreObdobieRequest = getKonaniePreObdobieRequest;
            return ((ServiceReference1.KonanieServicePort)(this)).getKonaniePreObdobieAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.getKonaniePodlaICOResponse1> ServiceReference1.KonanieServicePort.getKonaniePodlaICOAsync(ServiceReference1.getKonaniePodlaICORequest1 request)
        {
            return base.Channel.getKonaniePodlaICOAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.getKonaniePodlaICOResponse1> getKonaniePodlaICOAsync(ServiceReference1.getKonaniePodlaICORequest getKonaniePodlaICORequest)
        {
            ServiceReference1.getKonaniePodlaICORequest1 inValue = new ServiceReference1.getKonaniePodlaICORequest1();
            inValue.getKonaniePodlaICORequest = getKonaniePodlaICORequest;
            return ((ServiceReference1.KonanieServicePort)(this)).getKonaniePodlaICOAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.KonanieServicePortSoap11))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.KonanieServicePortSoap11))
            {
                return new System.ServiceModel.EndpointAddress("https://replik-ws.justice.sk/ru-verejnost-ws/");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return KonanieServicePortClient.GetBindingForEndpoint(EndpointConfiguration.KonanieServicePortSoap11);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return KonanieServicePortClient.GetEndpointAddress(EndpointConfiguration.KonanieServicePortSoap11);
        }
        
        public enum EndpointConfiguration
        {
            
            KonanieServicePortSoap11,
        }
    }
}
