//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReference2
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="datatypes.oznam.verejnost.ru.sk.hp.com", ConfigurationName="ServiceReference2.OznamServicePort")]
    public interface OznamServicePort
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference2.getVerejnyOznamDetailResponse1> getVerejnyOznamDetailAsync(ServiceReference2.getVerejnyOznamDetailRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference2.getVerejneOznamyPreObdobieResponse1> getVerejneOznamyPreObdobieAsync(ServiceReference2.getVerejneOznamyPreObdobieRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference2.getVerejneOznamyPodlaZnackyASuduResponse1> getVerejneOznamyPodlaZnackyASuduAsync(ServiceReference2.getVerejneOznamyPodlaZnackyASuduRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference2.getVerejneOznamyPodlaICOResponse1> getVerejneOznamyPodlaICOAsync(ServiceReference2.getVerejneOznamyPodlaICORequest1 request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="datatypes.oznam.verejnost.ru.sk.hp.com")]
    public partial class getVerejnyOznamDetailRequest
    {
        
        private long oznamIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long OznamId
        {
            get
            {
                return this.oznamIdField;
            }
            set
            {
                this.oznamIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(VerejnyOznam))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(VerejnyOznamSpravca))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(VerejnyOznamSud))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="datatypes.oznam.verejnost.ru.sk.hp.com")]
    public partial class VerejnyOznamInfo
    {
        
        private long oznamIdField;
        
        private OznamTyp oznamTypField;
        
        private string sudKodField;
        
        private string sudNazovField;
        
        private string spisovaZnackaSudnehoSpisuField;
        
        private long konanieIdField;
        
        private KonanieTyp konanieTypField;
        
        private System.DateTime datumVydaniaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long OznamId
        {
            get
            {
                return this.oznamIdField;
            }
            set
            {
                this.oznamIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public OznamTyp OznamTyp
        {
            get
            {
                return this.oznamTypField;
            }
            set
            {
                this.oznamTypField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string SudKod
        {
            get
            {
                return this.sudKodField;
            }
            set
            {
                this.sudKodField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string SudNazov
        {
            get
            {
                return this.sudNazovField;
            }
            set
            {
                this.sudNazovField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string SpisovaZnackaSudnehoSpisu
        {
            get
            {
                return this.spisovaZnackaSudnehoSpisuField;
            }
            set
            {
                this.spisovaZnackaSudnehoSpisuField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public long KonanieId
        {
            get
            {
                return this.konanieIdField;
            }
            set
            {
                this.konanieIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public KonanieTyp KonanieTyp
        {
            get
            {
                return this.konanieTypField;
            }
            set
            {
                this.konanieTypField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=7)]
        public System.DateTime DatumVydania
        {
            get
            {
                return this.datumVydaniaField;
            }
            set
            {
                this.datumVydaniaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="datatypes.oznam.verejnost.ru.sk.hp.com")]
    public enum OznamTyp
    {
        
        /// <remarks/>
        OZNAM_SUD,
        
        /// <remarks/>
        OZNAM_SPRAVCA,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="datatypes.oznam.verejnost.ru.sk.hp.com")]
    public enum KonanieTyp
    {
        
        /// <remarks/>
        KONKURZ,
        
        /// <remarks/>
        MALYKONKURZ,
        
        /// <remarks/>
        RESTRUKTURALIZACIA,
        
        /// <remarks/>
        INEKONANIA,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("ODDLZENIE-KONKURZ")]
        ODDLZENIEKONKURZ,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("ODDLZENIE-SPLATKOVYKALENDAR")]
        ODDLZENIESPLATKOVYKALENDAR,
        
        /// <remarks/>
        LIKVIDACIA,
        
        /// <remarks/>
        VPR,
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(VerejnyOznamSpravca))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(VerejnyOznamSud))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="datatypes.oznam.verejnost.ru.sk.hp.com")]
    public abstract partial class VerejnyOznam : VerejnyOznamInfo
    {
        
        private bool obsahujePrilohyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool ObsahujePrilohy
        {
            get
            {
                return this.obsahujePrilohyField;
            }
            set
            {
                this.obsahujePrilohyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="datatypes.oznam.verejnost.ru.sk.hp.com")]
    public partial class VerejnyOznamSpravca : VerejnyOznam
    {
        
        private DruhPodaniaSpravca druhPodaniaField;
        
        private string textField;
        
        private string spisovaZnackaSpravcovskehoSpisuField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public DruhPodaniaSpravca DruhPodania
        {
            get
            {
                return this.druhPodaniaField;
            }
            set
            {
                this.druhPodaniaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Text
        {
            get
            {
                return this.textField;
            }
            set
            {
                this.textField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string SpisovaZnackaSpravcovskehoSpisu
        {
            get
            {
                return this.spisovaZnackaSpravcovskehoSpisuField;
            }
            set
            {
                this.spisovaZnackaSpravcovskehoSpisuField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="datatypes.oznam.verejnost.ru.sk.hp.com")]
    public enum DruhPodaniaSpravca
    {
        
        /// <remarks/>
        OZNAM_O_TOM_KDE_A_KEDY_MOZNO_NAHLIADAT_DO_SPISU,
        
        /// <remarks/>
        OZNAM_O_ZVOLANI_SCHODZE_VERITELOV,
        
        /// <remarks/>
        ZAPISNICA_ZO_ZASADNUTIA_VERITELSKEHO_VYBORU,
        
        /// <remarks/>
        OZNAMENIA_SUVISIACE_S_DRAZBOU_MAJETKU_PODLIEHAJUCEHO_KONKURZU,
        
        /// <remarks/>
        SUPIS_VSEOBECNEJ_PODSTATY,
        
        /// <remarks/>
        SUPIS_ODDELENEJ_PODSTATY,
        
        /// <remarks/>
        ZVEREJNENIE_NAVRHU_CIASTKOVEHO_ROZVRHU_VYTAZKU_ZO_VSEOBECNEJ_PODSTATY,
        
        /// <remarks/>
        ZVEREJNENIE_NAVRHU_KONECNEHO_VYTAZKU_ZO_VSEOEBCNEJ_PODSTATY,
        
        /// <remarks/>
        DOPLNENIE_SUPISU_VSEOBECNEJ_PODSTATY_O_NOVU_SUPISOVU_ZLOZKU_MAJETKU,
        
        /// <remarks/>
        DOPLNENIE_SUPISU_ODDELENEJ_PODSTATY_O_NOVU_SUPISOVU_ZLOZKU_MAJETKU,
        
        /// <remarks/>
        PRERADENIE_SUPISOVEJ_ZLOZKY,
        
        /// <remarks/>
        PRIPISANIE_POZNAMKY_O_SPORNOM_ZAPISE,
        
        /// <remarks/>
        DOPLNENIE_ALEBO_ZMENA_POZNAMKY_O_SPORNOM_ZAPISE,
        
        /// <remarks/>
        VYMAZ_POZNAMKY_O_SPORNOM_ZAPISE,
        
        /// <remarks/>
        VYLUCENIE_SUPISOVEJ_ZLOZKY_MAJETKU_ZO_SUPISU,
        
        /// <remarks/>
        INE_ZVEREJNENIE,
        
        /// <remarks/>
        VYZVA_ZAHRANICNYM_VERITELOM_NA_PRIHLASENIE_POHLADAVOK,
        
        /// <remarks/>
        OZNAMENIE_CISLA_BANKOVEHO_UCTU_PRE_POTREBY_POPIERANIA_POHLADAVOK,
        
        /// <remarks/>
        OZNAMENIE_O_DORUCENI_PRIHLASKY_PO_UPLYNUTI_ZAKLADNEJ_PRIHLASOVACEJ_LEHOTY,
        
        /// <remarks/>
        OZNAMENIA_SUVISIACE_SO_SPENAZOVANIM_MAJETKU_PODLIEHAJUCEHO_KONKURZU,
        
        /// <remarks/>
        OZNAMENIE_O_ZOSTAVENI_ZOZNAMU_POHLADAVOK_PROTI_PODSTATE_A_ZAMERE_ZOSTAVIT_ROZVRH_ZO_VSEOBECNEJ_PODSTATY,
        
        /// <remarks/>
        OZNAMENIE_O_ZOSTAVENI_ZOZNAMU_POHLADAVOK_PROTI_PODSTATE_A_ZAMERE_ZOSTAVIT_ROZVRH_Z_ODDELENEJ_PODSTATY,
        
        /// <remarks/>
        ZVEREJNENIE_NAVRHU_CIASTKOVEHO_ROZVRHU_VYTAZKU_Z_ODDELENEJ_PODSTATY,
        
        /// <remarks/>
        ZVEREJNENIE_NAVRHU_KONECNEHO_ROZVRHU_VYTAZKU_Z_ODDELENEJ_PODSTATY,
        
        /// <remarks/>
        ZAPISNICA_ZO_ZASADNUTIA_SO_ZASTUPCOM_VERITELOV,
        
        /// <remarks/>
        OZNAM_O_ZOSTAVENI_NAVRHU_SPLATKOVEHO_KALENDARA,
        
        /// <remarks/>
        OZNAM_O_NEMOZNOSTI_ZOSTAVIT_NAVRH_SPLATKOVEHO_KALENDARA,
        
        /// <remarks/>
        OZNAM_O_ZRUSENI_KONKURZU_Z_DOVODU_ZE_DOSLO_K_SPLNENIU_ROZVRHU_VYTAZKU,
        
        /// <remarks/>
        OZNAM_O_ZRUSENI_KONKURZU_Z_DOVODU_ZE_KONKURZNA_PODSTATA_NEPOKRYJE_NAKLADY_KONKURZU,
        
        /// <remarks/>
        OZNAM_O_ZRUSENI_KONKURZU_Z_DOVODU_ZE_SA_DO_90_DNI_OD_VYHLASENIA_KONKURZU_NEPRIHLASIL_ZIADNY_VERITEL,
        
        /// <remarks/>
        OZNAM_O_ZRUSENI_KONKURZU_Z_DOVODU_ZE_POSTAVENIE_VSETKYCH_VERITELOV_AKO_UCASTNIKOV_KONANIA_ZANIKLO,
        
        /// <remarks/>
        OZNAM_O_SKONCENI_KONANIA_O_NAVRHU_NA_URCENIE_SK,
        
        /// <remarks/>
        OZNAM_O_UPLATNENI_NAMIETKY_VOCI_ZAPISU_MAJETKU_DO_SUPISU,
        
        /// <remarks/>
        PREBIEHAJUCA_LIKVIDACIA,
        
        /// <remarks/>
        LIKVIDACIA_PRIHLASOVANIE_POHLADAVOK,
        
        /// <remarks/>
        LIKVIDACIA_VYHOTOVENIE_ZOZNAMU_POHLADAVOK,
        
        /// <remarks/>
        LIKVIDACIA_VYHOTOVENIE_ZOZNAMU_MAJETKU,
        
        /// <remarks/>
        PODANIE_NAVRHU_NA_VYHLASENIE_KONKURZU_LIKVIDATOR,
        
        /// <remarks/>
        PRERUSENA_LIKVIDACIA_VYHLASENY_KONKURZ,
        
        /// <remarks/>
        PRERUSENA_LIKVIDACIA,
        
        /// <remarks/>
        SKONCENE_OZNAMENIM_LIKVIDATORA,
        
        /// <remarks/>
        SCHVALENIE_UCTOVNEJ_ZAVIERKY_KONECNEJ_SPRAVY_A_ROZDELENIA_ZOSTATKU,
        
        /// <remarks/>
        PREBIEHAJUCA_DODATOCNA_LIKVIDACIA,
        
        /// <remarks/>
        DODATOCNA_LIKVIDACIA_PRIHLASOVANIE_POHLADAVOK,
        
        /// <remarks/>
        DODATOCNA_LIKVIDACIA_VYHOTOVENIE_ZOZNAMU_POHLADAVOK,
        
        /// <remarks/>
        DODATOCNA_LIKVIDACIA_VYHOTOVENIE_ZOZNAMU_MAJETKU,
        
        /// <remarks/>
        DODATOCNA_LIKVIDACIA_PODANIE_NAVRHU_NA_VYHLASENIE_KONKURZU,
        
        /// <remarks/>
        DODATOCNA_LIKVIDACIA_PRERUSENE_VYHLASENY_KONKURZ,
        
        /// <remarks/>
        DODATOCNA_LIKVIDACIA_PRERUSENE,
        
        /// <remarks/>
        DODATOCNA_LIKVIDACIA_SKONCENE_OZNAMENIM_LIKVIDATORA,
        
        /// <remarks/>
        DODATOCNA_LIKVIDACIA_SCHVALENIE_UCTOVNEJ_ZAVIERKY_KONECNEJ_SPRAVY_A_ROZDELENIA_ZOSTATKU,
        
        /// <remarks/>
        ZVOLANIE_SCHVALOVACEJ_SCHODZE_VERITELOV_PO_SCHVALENI_PLANU_VERITELSKYM_VYBOROM,
        
        /// <remarks/>
        SPRAVA_O_POSTUPE_SPENAZOVANIA,
        
        /// <remarks/>
        ZAPISNICA_ZO_SCHODZE_VERITELOV,
        
        /// <remarks/>
        ZAPISNICA_ZO_SCHVALOVACEJ_SCHODZE_VERITELOV,
        
        /// <remarks/>
        ZVOLANIE_SCHODZE_VERITELSKEHO_VYBORU_NA_SCHVALENIE_PLANU,
        
        /// <remarks/>
        ZAZNAM_Z_ONLINE_SCHODZE_VERITELOV,
        
        /// <remarks/>
        OZNAMENIE_O_ZVEREJNENI_SUPISU_MAJETKU,
        
        /// <remarks/>
        UKONCENIE_PRIHLASOVANIA_POHLADAVOK,
        
        /// <remarks/>
        UKONCENIE_PRIESKUMU_POHLADAVOK,
        
        /// <remarks/>
        NEDEFINOVANE,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="datatypes.oznam.verejnost.ru.sk.hp.com")]
    public partial class VerejnyOznamSud : VerejnyOznam
    {
        
        private DruhPodaniaSud textDruhField;
        
        private string textPoucenieField;
        
        private string textHlavickaField;
        
        private string textOdovodnenieField;
        
        private string textOznamField;
        
        private string textRozhodnutieField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public DruhPodaniaSud TextDruh
        {
            get
            {
                return this.textDruhField;
            }
            set
            {
                this.textDruhField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string TextPoucenie
        {
            get
            {
                return this.textPoucenieField;
            }
            set
            {
                this.textPoucenieField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string TextHlavicka
        {
            get
            {
                return this.textHlavickaField;
            }
            set
            {
                this.textHlavickaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string TextOdovodnenie
        {
            get
            {
                return this.textOdovodnenieField;
            }
            set
            {
                this.textOdovodnenieField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string TextOznam
        {
            get
            {
                return this.textOznamField;
            }
            set
            {
                this.textOznamField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string TextRozhodnutie
        {
            get
            {
                return this.textRozhodnutieField;
            }
            set
            {
                this.textRozhodnutieField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="datatypes.oznam.verejnost.ru.sk.hp.com")]
    public enum DruhPodaniaSud
    {
        
        /// <remarks/>
        OZNAM,
        
        /// <remarks/>
        ROZHODNUTIE,
        
        /// <remarks/>
        ROZSUDOK,
        
        /// <remarks/>
        UZNESENIE,
        
        /// <remarks/>
        NEDEFINOVANE,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="datatypes.oznam.verejnost.ru.sk.hp.com")]
    public partial class getVerejnyOznamDetailResponse
    {
        
        private VerejnyOznam verejnyOznamField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public VerejnyOznam VerejnyOznam
        {
            get
            {
                return this.verejnyOznamField;
            }
            set
            {
                this.verejnyOznamField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getVerejnyOznamDetailRequest1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="datatypes.oznam.verejnost.ru.sk.hp.com", Order=0)]
        public ServiceReference2.getVerejnyOznamDetailRequest getVerejnyOznamDetailRequest;
        
        public getVerejnyOznamDetailRequest1()
        {
        }
        
        public getVerejnyOznamDetailRequest1(ServiceReference2.getVerejnyOznamDetailRequest getVerejnyOznamDetailRequest)
        {
            this.getVerejnyOznamDetailRequest = getVerejnyOznamDetailRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getVerejnyOznamDetailResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="datatypes.oznam.verejnost.ru.sk.hp.com", Order=0)]
        public ServiceReference2.getVerejnyOznamDetailResponse getVerejnyOznamDetailResponse;
        
        public getVerejnyOznamDetailResponse1()
        {
        }
        
        public getVerejnyOznamDetailResponse1(ServiceReference2.getVerejnyOznamDetailResponse getVerejnyOznamDetailResponse)
        {
            this.getVerejnyOznamDetailResponse = getVerejnyOznamDetailResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="datatypes.oznam.verejnost.ru.sk.hp.com")]
    public partial class getVerejneOznamyPreObdobieRequest
    {
        
        private System.DateTime datumOdField;
        
        private bool datumOdFieldSpecified;
        
        private System.DateTime datumDoField;
        
        private bool datumDoFieldSpecified;
        
        private int strankaField;
        
        private int vysledkovNaStrankuField;
        
        public getVerejneOznamyPreObdobieRequest()
        {
            this.strankaField = 0;
            this.vysledkovNaStrankuField = 10;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=0)]
        public System.DateTime DatumOd
        {
            get
            {
                return this.datumOdField;
            }
            set
            {
                this.datumOdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DatumOdSpecified
        {
            get
            {
                return this.datumOdFieldSpecified;
            }
            set
            {
                this.datumOdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=1)]
        public System.DateTime DatumDo
        {
            get
            {
                return this.datumDoField;
            }
            set
            {
                this.datumDoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DatumDoSpecified
        {
            get
            {
                return this.datumDoFieldSpecified;
            }
            set
            {
                this.datumDoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        [System.ComponentModel.DefaultValueAttribute(0)]
        public int Stranka
        {
            get
            {
                return this.strankaField;
            }
            set
            {
                this.strankaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        [System.ComponentModel.DefaultValueAttribute(10)]
        public int VysledkovNaStranku
        {
            get
            {
                return this.vysledkovNaStrankuField;
            }
            set
            {
                this.vysledkovNaStrankuField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="datatypes.oznam.verejnost.ru.sk.hp.com")]
    public partial class getVerejneOznamyPreObdobieResponse
    {
        
        private VerejnyOznamInfo[] verejnyOznamInfoListField;
        
        private long vysledkovCelkomField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public VerejnyOznamInfo[] VerejnyOznamInfoList
        {
            get
            {
                return this.verejnyOznamInfoListField;
            }
            set
            {
                this.verejnyOznamInfoListField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public long VysledkovCelkom
        {
            get
            {
                return this.vysledkovCelkomField;
            }
            set
            {
                this.vysledkovCelkomField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getVerejneOznamyPreObdobieRequest1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="datatypes.oznam.verejnost.ru.sk.hp.com", Order=0)]
        public ServiceReference2.getVerejneOznamyPreObdobieRequest getVerejneOznamyPreObdobieRequest;
        
        public getVerejneOznamyPreObdobieRequest1()
        {
        }
        
        public getVerejneOznamyPreObdobieRequest1(ServiceReference2.getVerejneOznamyPreObdobieRequest getVerejneOznamyPreObdobieRequest)
        {
            this.getVerejneOznamyPreObdobieRequest = getVerejneOznamyPreObdobieRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getVerejneOznamyPreObdobieResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="datatypes.oznam.verejnost.ru.sk.hp.com", Order=0)]
        public ServiceReference2.getVerejneOznamyPreObdobieResponse getVerejneOznamyPreObdobieResponse;
        
        public getVerejneOznamyPreObdobieResponse1()
        {
        }
        
        public getVerejneOznamyPreObdobieResponse1(ServiceReference2.getVerejneOznamyPreObdobieResponse getVerejneOznamyPreObdobieResponse)
        {
            this.getVerejneOznamyPreObdobieResponse = getVerejneOznamyPreObdobieResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="datatypes.oznam.verejnost.ru.sk.hp.com")]
    public partial class getVerejneOznamyPodlaZnackyASuduRequest
    {
        
        private string spisovaZnackaSudnehoSpisuField;
        
        private string sudKodField;
        
        private int strankaField;
        
        private int vysledkovNaStrankuField;
        
        public getVerejneOznamyPodlaZnackyASuduRequest()
        {
            this.strankaField = 0;
            this.vysledkovNaStrankuField = 10;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string SpisovaZnackaSudnehoSpisu
        {
            get
            {
                return this.spisovaZnackaSudnehoSpisuField;
            }
            set
            {
                this.spisovaZnackaSudnehoSpisuField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string SudKod
        {
            get
            {
                return this.sudKodField;
            }
            set
            {
                this.sudKodField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        [System.ComponentModel.DefaultValueAttribute(0)]
        public int Stranka
        {
            get
            {
                return this.strankaField;
            }
            set
            {
                this.strankaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        [System.ComponentModel.DefaultValueAttribute(10)]
        public int VysledkovNaStranku
        {
            get
            {
                return this.vysledkovNaStrankuField;
            }
            set
            {
                this.vysledkovNaStrankuField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="datatypes.oznam.verejnost.ru.sk.hp.com")]
    public partial class getVerejneOznamyPodlaZnackyASuduResponse
    {
        
        private VerejnyOznamInfo[] verejnyOznamInfoListField;
        
        private long vysledkovCelkomField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public VerejnyOznamInfo[] VerejnyOznamInfoList
        {
            get
            {
                return this.verejnyOznamInfoListField;
            }
            set
            {
                this.verejnyOznamInfoListField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public long VysledkovCelkom
        {
            get
            {
                return this.vysledkovCelkomField;
            }
            set
            {
                this.vysledkovCelkomField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getVerejneOznamyPodlaZnackyASuduRequest1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="datatypes.oznam.verejnost.ru.sk.hp.com", Order=0)]
        public ServiceReference2.getVerejneOznamyPodlaZnackyASuduRequest getVerejneOznamyPodlaZnackyASuduRequest;
        
        public getVerejneOznamyPodlaZnackyASuduRequest1()
        {
        }
        
        public getVerejneOznamyPodlaZnackyASuduRequest1(ServiceReference2.getVerejneOznamyPodlaZnackyASuduRequest getVerejneOznamyPodlaZnackyASuduRequest)
        {
            this.getVerejneOznamyPodlaZnackyASuduRequest = getVerejneOznamyPodlaZnackyASuduRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getVerejneOznamyPodlaZnackyASuduResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="datatypes.oznam.verejnost.ru.sk.hp.com", Order=0)]
        public ServiceReference2.getVerejneOznamyPodlaZnackyASuduResponse getVerejneOznamyPodlaZnackyASuduResponse;
        
        public getVerejneOznamyPodlaZnackyASuduResponse1()
        {
        }
        
        public getVerejneOznamyPodlaZnackyASuduResponse1(ServiceReference2.getVerejneOznamyPodlaZnackyASuduResponse getVerejneOznamyPodlaZnackyASuduResponse)
        {
            this.getVerejneOznamyPodlaZnackyASuduResponse = getVerejneOznamyPodlaZnackyASuduResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="datatypes.oznam.verejnost.ru.sk.hp.com")]
    public partial class getVerejneOznamyPodlaICORequest
    {
        
        private string icoField;
        
        private int strankaField;
        
        private int vysledkovNaStrankuField;
        
        public getVerejneOznamyPodlaICORequest()
        {
            this.strankaField = 0;
            this.vysledkovNaStrankuField = 10;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Ico
        {
            get
            {
                return this.icoField;
            }
            set
            {
                this.icoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        [System.ComponentModel.DefaultValueAttribute(0)]
        public int Stranka
        {
            get
            {
                return this.strankaField;
            }
            set
            {
                this.strankaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        [System.ComponentModel.DefaultValueAttribute(10)]
        public int VysledkovNaStranku
        {
            get
            {
                return this.vysledkovNaStrankuField;
            }
            set
            {
                this.vysledkovNaStrankuField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="datatypes.oznam.verejnost.ru.sk.hp.com")]
    public partial class getVerejneOznamyPodlaICOResponse
    {
        
        private VerejnyOznamInfo[] verejnyOznamInfoListField;
        
        private long vysledkovCelkomField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public VerejnyOznamInfo[] VerejnyOznamInfoList
        {
            get
            {
                return this.verejnyOznamInfoListField;
            }
            set
            {
                this.verejnyOznamInfoListField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public long VysledkovCelkom
        {
            get
            {
                return this.vysledkovCelkomField;
            }
            set
            {
                this.vysledkovCelkomField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getVerejneOznamyPodlaICORequest1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="datatypes.oznam.verejnost.ru.sk.hp.com", Order=0)]
        public ServiceReference2.getVerejneOznamyPodlaICORequest getVerejneOznamyPodlaICORequest;
        
        public getVerejneOznamyPodlaICORequest1()
        {
        }
        
        public getVerejneOznamyPodlaICORequest1(ServiceReference2.getVerejneOznamyPodlaICORequest getVerejneOznamyPodlaICORequest)
        {
            this.getVerejneOznamyPodlaICORequest = getVerejneOznamyPodlaICORequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getVerejneOznamyPodlaICOResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="datatypes.oznam.verejnost.ru.sk.hp.com", Order=0)]
        public ServiceReference2.getVerejneOznamyPodlaICOResponse getVerejneOznamyPodlaICOResponse;
        
        public getVerejneOznamyPodlaICOResponse1()
        {
        }
        
        public getVerejneOznamyPodlaICOResponse1(ServiceReference2.getVerejneOznamyPodlaICOResponse getVerejneOznamyPodlaICOResponse)
        {
            this.getVerejneOznamyPodlaICOResponse = getVerejneOznamyPodlaICOResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface OznamServicePortChannel : ServiceReference2.OznamServicePort, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class OznamServicePortClient : System.ServiceModel.ClientBase<ServiceReference2.OznamServicePort>, ServiceReference2.OznamServicePort
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public OznamServicePortClient() : 
                base(OznamServicePortClient.GetDefaultBinding(), OznamServicePortClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.OznamServicePortSoap11.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public OznamServicePortClient(EndpointConfiguration endpointConfiguration) : 
                base(OznamServicePortClient.GetBindingForEndpoint(endpointConfiguration), OznamServicePortClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public OznamServicePortClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(OznamServicePortClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public OznamServicePortClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(OznamServicePortClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public OznamServicePortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference2.getVerejnyOznamDetailResponse1> ServiceReference2.OznamServicePort.getVerejnyOznamDetailAsync(ServiceReference2.getVerejnyOznamDetailRequest1 request)
        {
            return base.Channel.getVerejnyOznamDetailAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference2.getVerejnyOznamDetailResponse1> getVerejnyOznamDetailAsync(ServiceReference2.getVerejnyOznamDetailRequest getVerejnyOznamDetailRequest)
        {
            ServiceReference2.getVerejnyOznamDetailRequest1 inValue = new ServiceReference2.getVerejnyOznamDetailRequest1();
            inValue.getVerejnyOznamDetailRequest = getVerejnyOznamDetailRequest;
            return ((ServiceReference2.OznamServicePort)(this)).getVerejnyOznamDetailAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference2.getVerejneOznamyPreObdobieResponse1> ServiceReference2.OznamServicePort.getVerejneOznamyPreObdobieAsync(ServiceReference2.getVerejneOznamyPreObdobieRequest1 request)
        {
            return base.Channel.getVerejneOznamyPreObdobieAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference2.getVerejneOznamyPreObdobieResponse1> getVerejneOznamyPreObdobieAsync(ServiceReference2.getVerejneOznamyPreObdobieRequest getVerejneOznamyPreObdobieRequest)
        {
            ServiceReference2.getVerejneOznamyPreObdobieRequest1 inValue = new ServiceReference2.getVerejneOznamyPreObdobieRequest1();
            inValue.getVerejneOznamyPreObdobieRequest = getVerejneOznamyPreObdobieRequest;
            return ((ServiceReference2.OznamServicePort)(this)).getVerejneOznamyPreObdobieAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference2.getVerejneOznamyPodlaZnackyASuduResponse1> ServiceReference2.OznamServicePort.getVerejneOznamyPodlaZnackyASuduAsync(ServiceReference2.getVerejneOznamyPodlaZnackyASuduRequest1 request)
        {
            return base.Channel.getVerejneOznamyPodlaZnackyASuduAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference2.getVerejneOznamyPodlaZnackyASuduResponse1> getVerejneOznamyPodlaZnackyASuduAsync(ServiceReference2.getVerejneOznamyPodlaZnackyASuduRequest getVerejneOznamyPodlaZnackyASuduRequest)
        {
            ServiceReference2.getVerejneOznamyPodlaZnackyASuduRequest1 inValue = new ServiceReference2.getVerejneOznamyPodlaZnackyASuduRequest1();
            inValue.getVerejneOznamyPodlaZnackyASuduRequest = getVerejneOznamyPodlaZnackyASuduRequest;
            return ((ServiceReference2.OznamServicePort)(this)).getVerejneOznamyPodlaZnackyASuduAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference2.getVerejneOznamyPodlaICOResponse1> ServiceReference2.OznamServicePort.getVerejneOznamyPodlaICOAsync(ServiceReference2.getVerejneOznamyPodlaICORequest1 request)
        {
            return base.Channel.getVerejneOznamyPodlaICOAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference2.getVerejneOznamyPodlaICOResponse1> getVerejneOznamyPodlaICOAsync(ServiceReference2.getVerejneOznamyPodlaICORequest getVerejneOznamyPodlaICORequest)
        {
            ServiceReference2.getVerejneOznamyPodlaICORequest1 inValue = new ServiceReference2.getVerejneOznamyPodlaICORequest1();
            inValue.getVerejneOznamyPodlaICORequest = getVerejneOznamyPodlaICORequest;
            return ((ServiceReference2.OznamServicePort)(this)).getVerejneOznamyPodlaICOAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.OznamServicePortSoap11))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.OznamServicePortSoap11))
            {
                return new System.ServiceModel.EndpointAddress("https://replik-ws.justice.sk/ru-verejnost-ws/");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return OznamServicePortClient.GetBindingForEndpoint(EndpointConfiguration.OznamServicePortSoap11);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return OznamServicePortClient.GetEndpointAddress(EndpointConfiguration.OznamServicePortSoap11);
        }
        
        public enum EndpointConfiguration
        {
            
            OznamServicePortSoap11,
        }
    }
}
